/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module PracticaSemaforo1 (
  input Q0,
  input Q1,
  input Q2,
  output \Q0* ,
  output \Q1* ,
  output \Q2* 
);
  wire s0;
  wire s1;
  assign s0 = ~ Q1;
  assign s1 = ~ Q2;
  assign \Q0*  = ((~ Q0 & s0 & s1) | (~ Q0 & s0 & Q2));
  assign \Q1*  = (s1 & s0 & Q0);
  assign \Q2*  = (s1 & Q1 & Q0);
endmodule
